# Generated by Django 4.0.1 on 2022-04-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut_projet',
            field=models.CharField(choices=[('En pause', 'Enpause'), ('Planifié', 'Planifie'), ('En cours', 'Encours'), ('Livré', 'Livre')], default='Planifié', max_length=50),
        ),
        migrations.CreateModel(
            name='Relation_Projet_Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.projet')),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tache')),
            ],
        ),
    ]
