# Generated by Django 4.0.1 on 2022-04-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_developpeur_responsable_remove_projet_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developpeur',
            name='taches_developpeur',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='projets_responsable',
        ),
    ]
