# Generated by Django 4.0.1 on 2022-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_developpeur_taches_developpeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut_tache',
            field=models.CharField(choices=[('En pause', 'Enpause'), ('Planifiée', 'Planifie'), ('En cours', 'Encours'), ('Réalisée', 'Realisee'), ('Validée', 'Valide')], default='Planifiée', max_length=50),
        ),
    ]
